### ISSUE TITLE
icons displayed abnormally/incorrect translation in zh-CN.yaml

### ISSUE THREAD

**Issue by lizihuasteven** [DirectoryLister/DirectoryLister#330] opened 2020-03-31 08:56 UTC
**Directory Lister Version**
3.0 rc4

**PHP Version**

PHP 4.3

**PHP Extensions**
PHP Extensions N/A

**HTTP Server**
NGINX

**Describe the bug**
When I updated dir-lister's version into rc4 from rc1, the icons weren't displayed correctly, all icons turned into one same appearence (an error icon I guess?)
So I looked at the .css files but I couldn't find any visible problems.
So after that I decided to re-upload the old rc1 version, PROBLEM SOLVED.
That was just very strange.

And also, translation file zh-CN.yaml (Simplified Chinese Translation, NOT Traditional Chinese) has many incorrect translations in it, I'm from China Beijing and I'm also a Computer Science student so please be relieved to the accuracy of my translation to these descriptions, you are welcomed use the translation I had modified.

home: 目录起始页

download: 下载

search: 搜索

file:

  name: 文件名

  size: 大小

  date: 日期

  info: 文件信息

powered_by: 基于

scroll_to_top: 回到顶部

error:

  directory_not_found: 目录不存在

  file_not_found: 文件未找到

  file_size_exceeded: 文件过大

  no_results_found: 未找到结果

  unexpected: 一个意料之外的问题发生了

enable_debugging: 启用调试以获取更多信息

**Comment by PHLAK** [comment] 2020-03-31 15:54
Try upgrading to `rc4` again then clear your cache directory.

    rm -rf app/cache/*

Let us know if this solves your problem.

**Comment by PHLAK** [comment] 2020-03-31 15:55
Also, thank you for the updated translations.

**Comment by lizihuasteven** [comment] 2020-03-31 16:00
Sorry I have no access to the server's command line interface, is deleting the cache directory in the server's FTP interface same as executing that command?

**Comment by PHLAK** [comment] 2020-03-31 16:10
Yes, deleting the contents of that folder vie FTP should work.

**Comment by lizihuasteven** [comment] 2020-03-31 16:12
OK then I can say that I have done it yesterday, it didn't work.

**Comment by PHLAK** [comment] 2020-03-31 16:16
Can you access your PHP logs? There's probably more information in the logs as to what the problem is.

**Comment by PHLAK** [comment] 2020-03-31 16:16
You could also try removing `index.php` and the `app` folder entirely. Then uploading the files from `rc4`.

**Comment by lizihuasteven** [comment] 2020-03-31 16:20
[31-Mar-2020 00:51:16 Asia/Chongqing] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 68647784 bytes) in /home/bae/app/dir-lister/app/src/Handlers/FileInfoHandler.php on line 67
[31-Mar-2020 01:15:45 Asia/Chongqing] PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0
[31-Mar-2020 01:50:38 Asia/Chongqing] PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0
[31-Mar-2020 01:51:32 Asia/Chongqing] PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0
[31-Mar-2020 03:51:24 Asia/Chongqing] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 130379904 bytes) in /home/bae/app/app/src/Handlers/FileInfoHandler.php on line 67
[31-Mar-2020 03:51:28 Asia/Chongqing] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 67892520 bytes) in /home/bae/app/app/src/Handlers/FileInfoHandler.php on line 67

**Comment by lizihuasteven** [comment] 2020-03-31 16:23
Yes before I upload new files from rc4 I deleted ALL dir-lister files except my documents

**Comment by lizihuasteven** [comment] 2020-03-31 16:35
Did someone else experience this problem before? Or it's just me having tough time with rc4? Maybe it's because the server I'm working on is quite exceptional.

**Comment by PHLAK** [comment] 2020-03-31 16:35
The memory limit issue may be fixed by increasing the `memory_limit` in your `php.ini` file.

See https://www.php.net/manual/en/ini.core.php#ini.sect.resource-limits for more information there.

However, this should not cause the icons to display incorrectly.

**Comment by PHLAK** [comment] 2020-03-31 16:36
>Did someone else experience this problem before? Or it's just me

This is the first I've heard of the icons not displaying properly.

**Comment by lizihuasteven** [comment] 2020-03-31 16:42
OK, thank you very much for trying so hard to help me figuring this out, although it wasn't solved be I think it's probably an isolated issue caused by some unknown incorrect parameters. I would try to investigate the bug's detailed information and I'll report it immediately as long as I figure what's the real problem.

**Closed** 2020-03-31 16:45 UTC
Labels: Bug
