### ISSUE TITLE
Set DARK_MODE=true doesn't work

### ISSUE THREAD

**Issue by CharlsBags** [DirectoryLister/DirectoryLister#434] opened 2020-07-23 09:52 UTC
**Directory Lister Version**

v3.4.0

**PHP Version**

7.2

**PHP Extensions**

nothing

**HTTP Server**

Apache

**Describe the bug**

Set DARK_MODE=true doesn't work

**Steps To Reproduce**

just install directorylister, copied env.example to .env and modified the parameter. the app works, but not dark mode

**Comment by PHLAK** [comment] 2020-07-23 16:20
Thanks. I've tracked the problem down to when container compilation is enabled (which is by default) the settings get cached with the container.

I'll try to push a fix out for this today but for now you can solve this by setting your configuration options the way you want them then clearing the cache (`rm -rf app/cache/*`).

**Comment by PHLAK** [comment] 2020-07-23 19:58
I've disabled container compilation in [v3.4.1](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.4.1) which should fix this issue for now. I'm also working on a proper fix that will allow container compilation without breaking configuration changes. This will be released in a future update.

**Closed by PHLAK** 2020-07-23 19:58 UTC
Labels: Bug

**Comment by DearTanker** [comment] 2020-08-06 12:40
This problem appeared again in v3.5. 
.env doesn't work.

**Comment by PHLAK** [comment] 2020-08-06 21:28
@DearTanker I am unable to reproduce this with a fresh installation of v3.5.0.

Try clearing your cache (`rm -rf app/cache/*`) and see if the problem is resolved. If not, you may need to delete `index.php` and the entire `app` folder and re-add them from a fresh v3.5.0 download.
