### ISSUE TITLE
Time Zone always UTC+0

### ISSUE THREAD

**Issue by luyurun** [DirectoryLister/DirectoryLister#895] opened 2022-05-25 07:04 UTC
### Directory Lister Version

v3.12.0

### PHP Version

v7.4.27

### PHP Extensions

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

### Web Server

IIS 10.0

### Describe the Bug

I set the ".env" file, added `timezone=Asia/Shanghai`
It should be UTC+8 timezone but it still force to UTC+0 timezone

**Comment by luyurun** [comment] 2022-05-26 19:15
I changed to `TIMEZONE=Asia/Shanghai` and deleted the "app/cache" folder
Still the same problem

**Comment by PHLAK** [comment] 2022-08-08 15:26
I've been unable to reproduce this issue. If you have any additional information please share it but closing this issue for now.

**Closed by PHLAK** 2022-08-08 15:26 UTC
Labels: Bug
