### ISSUE TITLE
open_basedir causes errors in main page 

### ISSUE THREAD

**Issue by ecko2010** [DirectoryLister/DirectoryLister#68] opened 2015-02-15 10:51 UTC
![15-02-2015 01-47-22](https://cloud.githubusercontent.com/assets/6710473/6202983/6b210230-b519-11e4-9e2f-c0b9fd7adf3e.jpg)
like this attach

**Comment by PHLAK** [comment] 2015-02-16 17:54
Closing as duplicate of #65

**Closed by PHLAK** 2015-02-16 17:54 UTC
