### ISSUE TITLE
Add option to search the current directory or include subdirectories

### ISSUE THREAD

**Issue by 952732328qwe** [DirectoryLister/DirectoryLister#478] opened 2020-09-17 04:04 UTC
For my website, it takes very very long time to give me results. I have more than 30 TB files in my site.It will be so good if you add a config to just search just current directory and it's own sub directories.

**Comment by PHLAK** [comment] 2020-09-17 15:26
Thanks, this is a duplicate of #312

**Closed by PHLAK** 2020-09-17 15:26 UTC
Labels: Duplicate, Enhancement
